---
title: "Exploratory Analysis"
output: 
  html_document:
    toc: true
    toc_float: true 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(tidyverse)
library(readxl)
library(plotly)
```

# Player Distribution 

```{r include=FALSE}
match_df = read_csv("./data/match_data.csv")|> 
  janitor::clean_names()
transfer_df = read_csv("./data/transfer.csv")|> 
  janitor::clean_names() 

player_df = read_excel("./data/player_game.xlsx", sheet = 1) |> 
  janitor::clean_names()|>
  rename(team = squad)
player_df$team = gsub("Manchester Utd", "Manchester United", player_df$team)
player_df$team = gsub("Newcastle Utd", "Newcastle", player_df$team)
player_df$team = gsub("Wolves", "Wolverhampton", player_df$team)
player_df$team = gsub("Cardiff City", "Cardiff", player_df$team)
player_df$team = gsub("Leicester City", "Leicester", player_df$team)

country_code_df = read.csv("./data/country_codes.csv") |> 
  janitor::clean_names() |> 
  rename(country = fifa) 
```

```{r include=FALSE}
GBR_df = country_code_df |> 
  filter(country == "ENG,NIR,SCO,WAL") 
GBR_df = data.frame(country = unlist(strsplit(as.character(GBR_df$country), ",")),
                    official_name_en = GBR_df$official_name_en,
                    region_name = GBR_df$region_name)
country_code_df = country_code_df |> 
  select(country, official_name_en, region_name) |> 
  bind_rows(GBR_df)

player_dist = player_df |>
  separate(nation, into = c("country_abbre", "country"), convert = TRUE) |> 
  select(country, player, team) |> 
  left_join(x = _, y = country_code_df) |> 
  drop_na()
```

### Player Distribution by Region

```{r}
player_dist |> 
  ggplot() + geom_bar(aes(x = region_name)) +
  labs(title = "PL Players by World Region", 
       x = "Region of the World",
       y = "Count of Players") + 
  scale_fill_viridis_d(option = "viridis")
```

### Player from top7 PL 2018-19

```{r player distribution by region}
player_dist |>
  count(region_name, team) |> 
  #filter(team %in% pl_1819_top7) |> 
  plot_ly(data = _,
        x = ~ team,
        y = ~ n,
        color = ~ region_name,
        colors = "Set2")  |> 
  add_markers(text = ~paste0('Football Club: ', team,
                      '</br>World Region: ', region_name,
                      '<br>Number in region: ', n),
        hoverinfo = "text")  |> 
  layout(showlegend = TRUE,
         title = "Player Distribution by Football Club",
         xaxis = list(title = "FC"),
         yaxis = list(title = "Number of Player by World Region)"))

```